//BOOT 0.0.2
WAIT 1.
CORE:PART:GETMODULE("kOSProcessor"):DOEVENT("Open Terminal").
COPYPATH("0:/SENSORS.KS", "1:/SENSORS.KS").
PRINT "BOOT COMPLETE".

WAIT 2.
SET RESET_LOG TO LIST("0:/LOGS/TESTLOG.CSV").
RESET_LOG:CLEAR().


WAIT 2.
RUN SENSORS.KS.
